In [2]:
import pandas as pd

df = pd.read_csv('graph_resilience.csv', encoding='utf-8')

selected_columns = ['graph', 'vertices', 'edges', 'density', 'count_of_wcc', 'v_largest_wcc', 'count_of_scc', 'v_largest_scc']

print('A1')
df[selected_columns]

A1

,graph,vertices,edges,density,count_of_wcc,v_largest_wcc,count_of_scc,v_largest_scc
0,CA-AstroPh,18772,396160,0.001124,290,0.953708,290,0.953708
1,ca-coauthors-dblp,540487,15245730,0.000104,1,1.000000,540487,0.000002
2,CA-GrQc,5242,28980,0.001055,355,0.793209,355,0.793209
3,com-orkut.ungraph,3072441,117185083,0.000025,1,1.000000,3072441,0.000000
4,com-youtube.ungraph,1134890,2987624,0.000005,1,1.000000,1134890,0.000001
5,Email-EuAll,265214,420045,0.000010,15836,0.847738,231000,0.128964
6,musae_git_edges,37700,0,0.000407,1,1.000000,37700,0.000027
7,soc-wiki-Vote,889,2916,0.007383,1,1.000000,889,0.001125
8,vk,3215720,0,0.000003,24337,0.983362,3215720,0.000000
9,web-Google,875713,5105039,0.000011,2746,0.977263,371764,0.496530
10,web-NotreDame,325729,1497134,0.000021,1,1.000000,203609,0.165684
11,web-Stanford,281903,2312497,0.000050,365,0.905507,29914,0.533985
12,Wiki-Vote,7115,103689,0.003981,24,0.993113,5816,0.182713

In [3]:
selected_columns = ['graph', 'diameter_ds', 'percentile_ds_500', 'percentile_ds_1000', 'diameter_s_500', 'diameter_s_1000', 'percentile_s_500', 'percentile_s_1000']

print('A2')
df[selected_columns]

A2

,graph,diameter_ds,percentile_ds_500,percentile_ds_1000,diameter_s_500,diameter_s_1000,percentile_s_500,percentile_s_1000
0,CA-AstroPh,13.94,5.63,5.46,4.94,5.66,4.78,5.28
1,ca-coauthors-dblp,22.80,7.22,7.06,4.80,5.34,4.48,5.12
2,CA-GrQc,16.52,8.00,8.00,7.50,8.42,7.12,7.92
3,com-orkut.ungraph,8.70,5.00,5.00,3.65,3.85,3.50,3.60
4,com-youtube.ungraph,24.00,7.00,7.00,4.02,4.14,3.38,3.20
5,Email-EuAll,14.00,5.00,5.00,2.78,3.16,2.62,3.00
6,musae_git_edges,10.64,4.00,4.00,3.50,3.90,2.80,3.06
7,soc-wiki-Vote,13.00,6.00,6.00,6.98,15.00,6.16,8.58
8,vk,18.80,7.00,7.00,4.70,5.30,4.30,5.10
9,web-Google,23.96,8.63,8.64,4.58,4.98,3.58,4.02
10,web-NotreDame,46.00,9.99,10.00,4.80,5.02,3.86,3.80
11,web-Stanford,164.00,10.06,10.00,3.98,4.34,3.08,3.24
12,Wiki-Vote,6.78,4.00,4.00,4.12,4.30,3.98,4.20

In [4]:
selected_columns = ['graph', 'triangles', 'avg_clustering', 'global_clustering']

print('A3')
df[selected_columns]

A3

                  graph  triangles  avg_clustering  global_clustering
0            CA-AstroPh    1351441          0.6306             0.3179
1     ca-coauthors-dblp  444095058          0.8019             0.6562
2               CA-GrQc      48260          0.5296             0.6297
3     com-orkut.ungraph  627584181          0.1666             0.0413
4   com-youtube.ungraph    3056386          0.0808             0.0062
5           Email-EuAll     267313          0.0671             0.0041
6       musae_git_edges     523810          0.1675             0.0124
7         soc-wiki-Vote       2119          0.1528             0.1273
8                    vk  108030337          0.0494             0.1095
9            web-Google   13391903          0.5143             0.0552
10        web-NotreDame    8910005          0.2346             0.0874
11         web-Stanford   11329473          0.5976             0.0086
12            Wiki-Vote     608389          0.1409             0.1255

In [5]:
selected_columns = ['graph', 'avg_clustering_wcc']

print('A4')
df[selected_columns]

A4

                  graph  avg_clustering_wcc
0            CA-AstroPh              0.6328
1     ca-coauthors-dblp              0.8019
2               CA-GrQc              0.5569
3     com-orkut.ungraph              0.1666
4   com-youtube.ungraph              0.0808
5           Email-EuAll              0.0791
6       musae_git_edges              0.1675
7         soc-wiki-Vote              0.1528
8                    vk              0.0499
9            web-Google              0.5190
10        web-NotreDame              0.2346
11         web-Stanford              0.6189
12            Wiki-Vote              0.1419

In [6]:
selected_columns = ['graph', 'min_deg', 'avg_deg', 'max_deg', 'auc_random', 'auc_degree']

print('A5')
df[selected_columns]

A5

                  graph  min_deg  avg_deg  max_deg  auc_random  auc_degree
0            CA-AstroPh      0.0    21.10    504.0    63.90800   21.497750
1     ca-coauthors-dblp      1.0    56.41   3299.0    71.43075   45.986500
2               CA-GrQc      0.0     5.53     81.0    35.11225    2.038000
3     com-orkut.ungraph      1.0    76.28  33313.0    77.70175   54.879250
4   com-youtube.ungraph      1.0     5.27  28754.0    45.92450    3.143976
5           Email-EuAll      0.0     2.75   7636.0     7.14980    0.090664
6       musae_git_edges      1.0    15.33   9458.0    65.74450    9.118000
7         soc-wiki-Vote      1.0     6.56    102.0    57.59325   11.211250
8                    vk      1.0    10.83   6503.0    60.08925   12.474500
9            web-Google      1.0     9.87   6332.0    53.00000    5.091250
10        web-NotreDame      1.0     6.69  10721.0    38.47125    0.195500
11         web-Stanford      1.0    14.14  38625.0    44.89050    4.047000
12            Wiki-Vote      1.0    28.32   1065.0    62.43875    8.474500

In [8]:
selected_columns = ['graph', 'auc_random', 'auc_degree']

print('B')
df[selected_columns]

B

                  graph  auc_random  auc_degree
0            CA-AstroPh    63.90800   21.497750
1     ca-coauthors-dblp    71.43075   45.986500
2               CA-GrQc    35.11225    2.038000
3     com-orkut.ungraph    77.70175   54.879250
4   com-youtube.ungraph    45.92450    3.143976
5           Email-EuAll     7.14980    0.090664
6       musae_git_edges    65.74450    9.118000
7         soc-wiki-Vote    57.59325   11.211250
8                    vk    60.08925   12.474500
9            web-Google    53.00000    5.091250
10        web-NotreDame    38.47125    0.195500
11         web-Stanford    44.89050    4.047000
12            Wiki-Vote    62.43875    8.474500