In [1]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\soc-wiki-Vote-landmarkBasic-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg estimated dist:'):
            results[(current_landmarks, 'Avg estimated dist')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg relative error:'):
            results[(current_landmarks, 'Avg relative error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg time algorithm:'):
            results[(current_landmarks, 'Avg time algorithm (ms)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                  SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         file size (MB)                       0.00                 0.00
          precomputing time (ms)               0.00                 1.00
8         file size (MB)                       0.01                 0.01
          precomputing time (ms)               1.00                 1.00
16        file size (MB)                       0.01                 0.01
          precomputing time (ms)               1.00                 1.00
32        file size (MB)                       0.03                 0.03
          precomputing time (ms)               2.00                 2.00
64        file size (MB)                       0.05                 0.05
          precomputing time (ms)               4.00                 3.00
128       file size (MB)                       0.11                 0.11
          precomputing time (ms)               7.00                 7.00

                                  SelectBestCoverage
landmarks metric
4         file size (MB)                        0.00
          precomputing time (ms)               19.00
8         file size (MB)                        0.01
          precomputing time (ms)               20.00
16        file size (MB)                        0.01
          precomputing time (ms)               20.00
32        file size (MB)                        0.03
          precomputing time (ms)               21.00
64        file size (MB)                        0.05
          precomputing time (ms)               42.00
128       file size (MB)                        0.11
          precomputing time (ms)               64.00

In [2]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\soc-wiki-Vote-landmarkShortcut-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg estimated dist:'):
            results[(current_landmarks, 'Avg estimated dist')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg relative error:'):
            results[(current_landmarks, 'Avg relative error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg time algorithm:'):
            results[(current_landmarks, 'Avg time algorithm (ms)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                  SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         file size (MB)                       0.01                 0.01
          precomputing time (ms)               0.00                 1.00
8         file size (MB)                       0.03                 0.03
          precomputing time (ms)               1.00                 1.00
16        file size (MB)                       0.05                 0.05
          precomputing time (ms)               1.00                 2.00
32        file size (MB)                       0.11                 0.11
          precomputing time (ms)               3.00                 3.00
64        file size (MB)                       0.22                 0.22
          precomputing time (ms)               5.00                 6.00
128       file size (MB)                       0.43                 0.43
          precomputing time (ms)              10.00                10.00

                                  SelectBestCoverage
landmarks metric
4         file size (MB)                        0.01
          precomputing time (ms)               22.00
8         file size (MB)                        0.03
          precomputing time (ms)               21.00
16        file size (MB)                        0.05
          precomputing time (ms)               23.00
32        file size (MB)                        0.11
          precomputing time (ms)               23.00
64        file size (MB)                        0.22
          precomputing time (ms)               46.00
128       file size (MB)                        0.43
          precomputing time (ms)               71.00

In [3]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\web-Google-landmarkBasic-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg estimated dist:'):
            results[(current_landmarks, 'Avg estimated dist')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg relative error:'):
            results[(current_landmarks, 'Avg relative error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg time algorithm:'):
            results[(current_landmarks, 'Avg time algorithm (ms)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                  SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         file size (MB)                       3.34                 3.34
          precomputing time (ms)            1002.00              1143.00
8         file size (MB)                       6.68                 6.68
          precomputing time (ms)            1043.00              1491.00
16        file size (MB)                      13.36                13.36
          precomputing time (ms)            1938.00              2394.00
32        file size (MB)                      26.72                26.72
          precomputing time (ms)            3520.00              3889.00
64        file size (MB)                      53.45                53.45
          precomputing time (ms)            6883.00              7470.00
128       file size (MB)                     106.90               106.90
          precomputing time (ms)           13193.00             13878.00

                                  SelectBestCoverage
landmarks metric
4         file size (MB)                        3.34
          precomputing time (ms)            31962.00
8         file size (MB)                        6.68
          precomputing time (ms)            32558.00
16        file size (MB)                       13.36
          precomputing time (ms)            32951.00
32        file size (MB)                       26.72
          precomputing time (ms)            34482.00
64        file size (MB)                       53.45
          precomputing time (ms)            37900.00
128       file size (MB)                      106.90
          precomputing time (ms)            43163.00

In [4]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\web-Google-landmarkShortcut-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg estimated dist:'):
            results[(current_landmarks, 'Avg estimated dist')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg relative error:'):
            results[(current_landmarks, 'Avg relative error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg time algorithm:'):
            results[(current_landmarks, 'Avg time algorithm (ms)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                  SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         file size (MB)                      13.36                13.36
          precomputing time (ms)             967.00              1363.00
8         file size (MB)                      26.72                26.72
          precomputing time (ms)            1525.00              1811.00
16        file size (MB)                      53.45                53.45
          precomputing time (ms)            2846.00              3117.00
32        file size (MB)                     106.90               106.90
          precomputing time (ms)            4899.00              5247.00
64        file size (MB)                     213.80               213.80
          precomputing time (ms)            9357.00              9870.00
128       file size (MB)                     427.59               427.59
          precomputing time (ms)           18699.00             18985.00

                                  SelectBestCoverage
landmarks metric
4         file size (MB)                       13.36
          precomputing time (ms)            32574.00
8         file size (MB)                       26.72
          precomputing time (ms)            31530.00
16        file size (MB)                       53.45
          precomputing time (ms)            34377.00
32        file size (MB)                      106.90
          precomputing time (ms)            36832.00
64        file size (MB)                      213.80
          precomputing time (ms)            40405.00
128       file size (MB)                      427.59
          precomputing time (ms)            51288.00

In [5]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\web-NotreDame-landmarkBasic-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg estimated dist:'):
            results[(current_landmarks, 'Avg estimated dist')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg relative error:'):
            results[(current_landmarks, 'Avg relative error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg time algorithm:'):
            results[(current_landmarks, 'Avg time algorithm (ms)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                  SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         file size (MB)                       1.24                 1.24
          precomputing time (ms)             222.00               395.00
8         file size (MB)                       2.49                 2.49
          precomputing time (ms)             306.00               381.00
16        file size (MB)                       4.97                 4.97
          precomputing time (ms)             571.00               639.00
32        file size (MB)                       9.94                 9.94
          precomputing time (ms)            1014.00              1083.00
64        file size (MB)                      19.88                19.88
          precomputing time (ms)            1963.00              2137.00
128       file size (MB)                      39.76                39.76
          precomputing time (ms)            3837.00              3908.00

                                  SelectBestCoverage
landmarks metric
4         file size (MB)                        1.24
          precomputing time (ms)             9732.00
8         file size (MB)                        2.49
          precomputing time (ms)            10423.00
16        file size (MB)                        4.97
          precomputing time (ms)            11240.00
32        file size (MB)                        9.94
          precomputing time (ms)            11425.00
64        file size (MB)                       19.88
          precomputing time (ms)            23188.00
128       file size (MB)                       39.76
          precomputing time (ms)            34888.00

In [6]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\web-NotreDame-landmarkShortcut-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg estimated dist:'):
            results[(current_landmarks, 'Avg estimated dist')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg relative error:'):
            results[(current_landmarks, 'Avg relative error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg time algorithm:'):
            results[(current_landmarks, 'Avg time algorithm (ms)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                  SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         file size (MB)                       4.97                 4.97
          precomputing time (ms)             279.00               386.00
8         file size (MB)                       9.94                 9.94
          precomputing time (ms)             423.00               519.00
16        file size (MB)                      19.88                19.88
          precomputing time (ms)             787.00               872.00
32        file size (MB)                      39.76                39.76
          precomputing time (ms)            1420.00              1453.00
64        file size (MB)                      79.52                79.52
          precomputing time (ms)            2721.00              2874.00
128       file size (MB)                     159.05               159.05
          precomputing time (ms)            5421.00              5370.00

                                  SelectBestCoverage
landmarks metric
4         file size (MB)                        4.97
          precomputing time (ms)            10924.00
8         file size (MB)                        9.94
          precomputing time (ms)            10770.00
16        file size (MB)                       19.88
          precomputing time (ms)            10882.00
32        file size (MB)                       39.76
          precomputing time (ms)            11475.00
64        file size (MB)                       79.52
          precomputing time (ms)            22854.00
128       file size (MB)                      159.05
          precomputing time (ms)            35204.00