In [1]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\soc-wiki-Vote-landmarkBasic-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg actual distance time:'):
            results[(current_landmarks, 'Avg actual distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Mean absolute error:'):
            results[(current_landmarks, 'Mean absolute error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg estimated distance time:'):
            results[(current_landmarks, 'Avg estimated distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                       SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       2.68                 0.34
          file size (MB)                            0.00                 0.00
          precomputing time (ms)                    0.00                 1.00
8         Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       1.91                 0.42
          file size (MB)                            0.01                 0.01
          precomputing time (ms)                    1.00                 1.00
16        Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       1.32                 0.20
          file size (MB)                            0.01                 0.01
          precomputing time (ms)                    1.00                 1.00
32        Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       0.91                 0.11
          file size (MB)                            0.03                 0.03
          precomputing time (ms)                    2.00                 2.00
64        Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       0.83                 0.06
          file size (MB)                            0.05                 0.05
          precomputing time (ms)                    4.00                 3.00
128       Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       0.48                 0.01
          file size (MB)                            0.11                 0.11
          precomputing time (ms)                    7.00                 7.00

                                       SelectBestCoverage
landmarks metric
4         Avg actual distance time                   0.00
          Avg estimated distance time                0.00
          Mean absolute error                        0.36
          file size (MB)                             0.00
          precomputing time (ms)                    19.00
8         Avg actual distance time                   0.00
          Avg estimated distance time                0.00
          Mean absolute error                        0.27
          file size (MB)                             0.01
          precomputing time (ms)                    20.00
16        Avg actual distance time                   0.00
          Avg estimated distance time                0.00
          Mean absolute error                        0.20
          file size (MB)                             0.01
          precomputing time (ms)                    20.00
32        Avg actual distance time                   0.00
          Avg estimated distance time                0.00
          Mean absolute error                        0.10
          file size (MB)                             0.03
          precomputing time (ms)                    21.00
64        Avg actual distance time                   0.00
          Avg estimated distance time                0.00
          Mean absolute error                        0.02
          file size (MB)                             0.05
          precomputing time (ms)                    42.00
128       Avg actual distance time                   0.00
          Avg estimated distance time                0.00
          Mean absolute error                        0.01
          file size (MB)                             0.11
          precomputing time (ms)                    64.00

In [2]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\soc-wiki-Vote-landmarkShortcut-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg actual distance time:'):
            results[(current_landmarks, 'Avg actual distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Mean absolute error:'):
            results[(current_landmarks, 'Mean absolute error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg estimated distance time:'):
            results[(current_landmarks, 'Avg estimated distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                       SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       0.18                 0.26
          file size (MB)                            0.01                 0.01
          precomputing time (ms)                    0.00                 1.00
8         Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       0.09                 0.10
          file size (MB)                            0.03                 0.03
          precomputing time (ms)                    1.00                 1.00
16        Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       0.06                 0.03
          file size (MB)                            0.05                 0.05
          precomputing time (ms)                    1.00                 2.00
32        Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       0.03                 0.01
          file size (MB)                            0.11                 0.11
          precomputing time (ms)                    3.00                 3.00
64        Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               0.04                 0.02
          Mean absolute error                       0.00                 0.00
          file size (MB)                            0.22                 0.22
          precomputing time (ms)                    5.00                 6.00
128       Avg actual distance time                  0.00                 0.00
          Avg estimated distance time               1.02                 1.00
          Mean absolute error                       0.00                 0.01
          file size (MB)                            0.43                 0.43
          precomputing time (ms)                   10.00                10.00

                                       SelectBestCoverage
landmarks metric
4         Avg actual distance time                   0.00
          Avg estimated distance time                0.00
          Mean absolute error                        0.24
          file size (MB)                             0.01
          precomputing time (ms)                    22.00
8         Avg actual distance time                   0.00
          Avg estimated distance time                0.00
          Mean absolute error                        0.14
          file size (MB)                             0.03
          precomputing time (ms)                    21.00
16        Avg actual distance time                   0.00
          Avg estimated distance time                0.00
          Mean absolute error                        0.06
          file size (MB)                             0.05
          precomputing time (ms)                    23.00
32        Avg actual distance time                   0.00
          Avg estimated distance time                0.00
          Mean absolute error                        0.01
          file size (MB)                             0.11
          precomputing time (ms)                    23.00
64        Avg actual distance time                   0.00
          Avg estimated distance time                0.01
          Mean absolute error                        0.02
          file size (MB)                             0.22
          precomputing time (ms)                    46.00
128       Avg actual distance time                   0.00
          Avg estimated distance time                1.03
          Mean absolute error                        0.01
          file size (MB)                             0.43
          precomputing time (ms)                    71.00

In [3]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\web-Google-landmarkBasic-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg actual distance time:'):
            results[(current_landmarks, 'Avg actual distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Mean absolute error:'):
            results[(current_landmarks, 'Mean absolute error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg estimated distance time:'):
            results[(current_landmarks, 'Avg estimated distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                       SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         Avg actual distance time              227.8200             216.7100
          Avg estimated distance time             0.0000               0.0000
          Mean absolute error                     3.8866               1.5938
          file size (MB)                          3.3400               3.3400
          precomputing time (ms)               1002.0000            1143.0000
8         Avg actual distance time              223.0500             185.2500
          Avg estimated distance time             0.0000               0.0000
          Mean absolute error                     3.3434               1.3297
          file size (MB)                          6.6800               6.6800
          precomputing time (ms)               1043.0000            1491.0000
16        Avg actual distance time              201.2900             216.7800
          Avg estimated distance time             0.0000               0.0000
          Mean absolute error                     3.9072               1.2626
          file size (MB)                         13.3600              13.3600
          precomputing time (ms)               1938.0000            2394.0000
32        Avg actual distance time              209.1100             191.6600
          Avg estimated distance time             0.0000               0.0000
          Mean absolute error                     3.2021               0.7789
          file size (MB)                         26.7200              26.7200
          precomputing time (ms)               3520.0000            3889.0000
64        Avg actual distance time              215.3500             217.2800
          Avg estimated distance time             0.0000               0.0000
          Mean absolute error                     2.8723               0.1304
          file size (MB)                         53.4500              53.4500
          precomputing time (ms)               6883.0000            7470.0000
128       Avg actual distance time              206.4900             216.4700
          Avg estimated distance time             0.0000               0.0000
          Mean absolute error                     2.3958               0.0417
          file size (MB)                        106.9000             106.9000
          precomputing time (ms)              13193.0000           13878.0000

                                       SelectBestCoverage
landmarks metric
4         Avg actual distance time               218.4800
          Avg estimated distance time              0.0000
          Mean absolute error                      0.4286
          file size (MB)                           3.3400
          precomputing time (ms)               31962.0000
8         Avg actual distance time               217.3200
          Avg estimated distance time              0.0000
          Mean absolute error                      0.2766
          file size (MB)                           6.6800
          precomputing time (ms)               32558.0000
16        Avg actual distance time               210.0400
          Avg estimated distance time              0.0000
          Mean absolute error                      0.1809
          file size (MB)                          13.3600
          precomputing time (ms)               32951.0000
32        Avg actual distance time               221.2500
          Avg estimated distance time              0.0000
          Mean absolute error                      0.0978
          file size (MB)                          26.7200
          precomputing time (ms)               34482.0000
64        Avg actual distance time               203.5200
          Avg estimated distance time              0.0000
          Mean absolute error                      0.0833
          file size (MB)                          53.4500
          precomputing time (ms)               37900.0000
128       Avg actual distance time               231.1500
          Avg estimated distance time              0.0000
          Mean absolute error                      0.1684
          file size (MB)                         106.9000
          precomputing time (ms)               43163.0000

In [4]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\web-Google-landmarkShortcut-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg actual distance time:'):
            results[(current_landmarks, 'Avg actual distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Mean absolute error:'):
            results[(current_landmarks, 'Mean absolute error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg estimated distance time:'):
            results[(current_landmarks, 'Avg estimated distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                       SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         Avg actual distance time              205.1100             219.8200
          Avg estimated distance time             0.0000               0.0000
          Mean absolute error                     0.2784               0.2660
          file size (MB)                         13.3600              13.3600
          precomputing time (ms)                967.0000            1363.0000
8         Avg actual distance time              243.4600             202.1200
          Avg estimated distance time             0.0000               0.0000
          Mean absolute error                     0.1939               0.1546
          file size (MB)                         26.7200              26.7200
          precomputing time (ms)               1525.0000            1811.0000
16        Avg actual distance time              204.0900             198.1800
          Avg estimated distance time             0.0000               0.0000
          Mean absolute error                     0.1277               0.1158
          file size (MB)                         53.4500              53.4500
          precomputing time (ms)               2846.0000            3117.0000
32        Avg actual distance time              212.3600             203.7900
          Avg estimated distance time             0.0000               0.0000
          Mean absolute error                     0.0421               0.0638
          file size (MB)                        106.9000             106.9000
          precomputing time (ms)               4899.0000            5247.0000
64        Avg actual distance time              208.3800             205.8800
          Avg estimated distance time             1.0000               0.6300
          Mean absolute error                     0.0323               0.0421
          file size (MB)                        213.8000             213.8000
          precomputing time (ms)               9357.0000            9870.0000
128       Avg actual distance time              218.2800             208.8800
          Avg estimated distance time             2.4600               1.6300
          Mean absolute error                     0.0306               0.0105
          file size (MB)                        427.5900             427.5900
          precomputing time (ms)              18699.0000           18985.0000

                                       SelectBestCoverage
landmarks metric
4         Avg actual distance time               227.9000
          Avg estimated distance time              0.0000
          Mean absolute error                      0.2083
          file size (MB)                          13.3600
          precomputing time (ms)               32574.0000
8         Avg actual distance time               206.8800
          Avg estimated distance time              0.0000
          Mean absolute error                      0.1562
          file size (MB)                          26.7200
          precomputing time (ms)               31530.0000
16        Avg actual distance time               193.0700
          Avg estimated distance time              0.0000
          Mean absolute error                      0.0632
          file size (MB)                          53.4500
          precomputing time (ms)               34377.0000
32        Avg actual distance time               217.3900
          Avg estimated distance time              0.0000
          Mean absolute error                      0.0612
          file size (MB)                         106.9000
          precomputing time (ms)               36832.0000
64        Avg actual distance time               207.3600
          Avg estimated distance time              0.8400
          Mean absolute error                      0.0312
          file size (MB)                         213.8000
          precomputing time (ms)               40405.0000
128       Avg actual distance time               222.8700
          Avg estimated distance time              2.0700
          Mean absolute error                      0.0000
          file size (MB)                         427.5900
          precomputing time (ms)               51288.0000

In [5]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\web-NotreDame-landmarkBasic-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg actual distance time:'):
            results[(current_landmarks, 'Avg actual distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Mean absolute error:'):
            results[(current_landmarks, 'Mean absolute error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg estimated distance time:'):
            results[(current_landmarks, 'Avg estimated distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                       SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         Avg actual distance time                 69.34                65.16
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       2.68                 0.43
          file size (MB)                            1.24                 1.24
          precomputing time (ms)                  222.00               395.00
8         Avg actual distance time                 55.97                63.58
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       3.27                 0.55
          file size (MB)                            2.49                 2.49
          precomputing time (ms)                  306.00               381.00
16        Avg actual distance time                 66.78                59.84
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       3.40                 0.11
          file size (MB)                            4.97                 4.97
          precomputing time (ms)                  571.00               639.00
32        Avg actual distance time                 58.85                64.91
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       2.37                 0.18
          file size (MB)                            9.94                 9.94
          precomputing time (ms)                 1014.00              1083.00
64        Avg actual distance time                 61.80                62.44
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       2.38                 0.13
          file size (MB)                           19.88                19.88
          precomputing time (ms)                 1963.00              2137.00
128       Avg actual distance time                 59.86                63.33
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       1.82                 0.07
          file size (MB)                           39.76                39.76
          precomputing time (ms)                 3837.00              3908.00

                                       SelectBestCoverage
landmarks metric
4         Avg actual distance time                  59.89
          Avg estimated distance time                0.00
          Mean absolute error                        0.10
          file size (MB)                             1.24
          precomputing time (ms)                  9732.00
8         Avg actual distance time                  62.82
          Avg estimated distance time                0.00
          Mean absolute error                        0.10
          file size (MB)                             2.49
          precomputing time (ms)                 10423.00
16        Avg actual distance time                  59.38
          Avg estimated distance time                0.00
          Mean absolute error                        0.10
          file size (MB)                             4.97
          precomputing time (ms)                 11240.00
32        Avg actual distance time                  69.10
          Avg estimated distance time                0.00
          Mean absolute error                        0.04
          file size (MB)                             9.94
          precomputing time (ms)                 11425.00
64        Avg actual distance time                  66.11
          Avg estimated distance time                0.00
          Mean absolute error                        0.03
          file size (MB)                            19.88
          precomputing time (ms)                 23188.00
128       Avg actual distance time                  68.21
          Avg estimated distance time                0.00
          Mean absolute error                        0.08
          file size (MB)                            39.76
          precomputing time (ms)                 34888.00

In [6]:
import pandas as pd
import re
from collections import defaultdict

filepath = r'..\graph\landmarkAlgo\benchmark\output\web-NotreDame-landmarkShortcut-bench.txt'

with open(filepath, 'r') as f:
    lines = f.readlines()

results = defaultdict(dict)

current_algorithm = None
current_landmarks = None

for line in lines:
    line = line.strip()

    if line.startswith('graph_theory/graph/landmarkAlgo'):
        current_algorithm = line.split('.')[-1]

    elif line.startswith('landmarks:'):
        current_landmarks = int(re.search(r'\d+', line).group())

    elif current_algorithm and current_landmarks:
        if line.startswith('precomputing time:'):
            results[(current_landmarks, 'precomputing time (ms)')][current_algorithm] = int(re.search(r'\d+', line).group())
        elif line.startswith('Avg actual distance time:'):
            results[(current_landmarks, 'Avg actual distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Mean absolute error:'):
            results[(current_landmarks, 'Mean absolute error')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('Avg estimated distance time:'):
            results[(current_landmarks, 'Avg estimated distance time')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())
        elif line.startswith('file size:'):
            results[(current_landmarks, 'file size (MB)')][current_algorithm] = float(re.search(r'\d+\.\d+', line).group())

df = pd.DataFrame(results).T
df.index.names = ['landmarks', 'metric']
df = df.sort_index()

df

                                       SelectRandomNodes  SelectHighestDegree  \
landmarks metric
4         Avg actual distance time                 61.88                69.77
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       0.18                 0.20
          file size (MB)                            4.97                 4.97
          precomputing time (ms)                  279.00               386.00
8         Avg actual distance time                 60.03                61.75
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       0.05                 0.14
          file size (MB)                            9.94                 9.94
          precomputing time (ms)                  423.00               519.00
16        Avg actual distance time                 48.54                63.08
          Avg estimated distance time               0.00                 0.00
          Mean absolute error                       0.03                 0.04
          file size (MB)                           19.88                19.88
          precomputing time (ms)                  787.00               872.00
32        Avg actual distance time                 68.17                63.21
          Avg estimated distance time               0.04                 0.04
          Mean absolute error                       0.02                 0.02
          file size (MB)                           39.76                39.76
          precomputing time (ms)                 1420.00              1453.00
64        Avg actual distance time                 68.24                62.78
          Avg estimated distance time               1.08                 1.01
          Mean absolute error                       0.00                 0.05
          file size (MB)                           79.52                79.52
          precomputing time (ms)                 2721.00              2874.00
128       Avg actual distance time                 64.16                61.84
          Avg estimated distance time               2.68                 2.29
          Mean absolute error                       0.02                 0.00
          file size (MB)                          159.05               159.05
          precomputing time (ms)                 5421.00              5370.00

                                       SelectBestCoverage
landmarks metric
4         Avg actual distance time                  64.17
          Avg estimated distance time                0.00
          Mean absolute error                        0.06
          file size (MB)                             4.97
          precomputing time (ms)                 10924.00
8         Avg actual distance time                  69.82
          Avg estimated distance time                0.00
          Mean absolute error                        0.09
          file size (MB)                             9.94
          precomputing time (ms)                 10770.00
16        Avg actual distance time                  65.06
          Avg estimated distance time                0.00
          Mean absolute error                        0.01
          file size (MB)                            19.88
          precomputing time (ms)                 10882.00
32        Avg actual distance time                  59.91
          Avg estimated distance time                0.02
          Mean absolute error                        0.02
          file size (MB)                            39.76
          precomputing time (ms)                 11475.00
64        Avg actual distance time                  58.72
          Avg estimated distance time                0.96
          Mean absolute error                        0.00
          file size (MB)                            79.52
          precomputing time (ms)                 22854.00
128       Avg actual distance time                  67.58
          Avg estimated distance time                2.27
          Mean absolute error                        0.01
          file size (MB)                           159.05
          precomputing time (ms)                 35204.00